#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LastFM.Resource", IsApplication=true)]

namespace LastFM
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001e
			public const int SimilarName = 2131099678;
			
			// aapt resource value: 0x7f060015
			public const int artistSearchtext = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int btnAlbumResult = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int btnArtistResult = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int btnArtistSearch = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int btnSongResult = 2131099673;
			
			// aapt resource value: 0x7f060011
			public const int formedYearArtist = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int ivAlbumImage = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int ivArtistImage = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int ivSelectedAlbumImage = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int ivSelectedArtistImage = 2131099663;
			
			// aapt resource value: 0x7f060025
			public const int ivSelectedTrackImage = 2131099685;
			
			// aapt resource value: 0x7f06001f
			public const int ivTrackImage = 2131099679;
			
			// aapt resource value: 0x7f06001b
			public const int lvAlbumSearchResult = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int lvArtistSearchResult = 2131099674;
			
			// aapt resource value: 0x7f06000c
			public const int lvListArtistName = 2131099660;
			
			// aapt resource value: 0x7f060021
			public const int lvTrackArtistName = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int lvTrackName = 2131099680;
			
			// aapt resource value: 0x7f06001c
			public const int lvTrackSearchResult = 2131099676;
			
			// aapt resource value: 0x7f060012
			public const int publishedYearArtist = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int scrollAlbumView = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int scrollArtistView = 2131099661;
			
			// aapt resource value: 0x7f060022
			public const int scrollTrackView = 2131099682;
			
			// aapt resource value: 0x7f060013
			public const int similarHeader = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int similarImageList = 2131099677;
			
			// aapt resource value: 0x7f060014
			public const int similarList = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int tvAlbumName = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int tvAlbumTrackName = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int tvDuration = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int tvRealeseDate = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int tvSelectedAlbumName = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int tvSelectedArtistName = 2131099654;
			
			// aapt resource value: 0x7f060024
			public const int tvSelectedTrackArtistName = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int tvSelectedTrackName = 2131099683;
			
			// aapt resource value: 0x7f060027
			public const int tvTrackBio = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int tvTrackDuration = 2131099686;
			
			// aapt resource value: 0x7f06000a
			public const int tvTracks = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int tvalbumBio = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int twArtistBio = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int twArtistName = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int albumListTemplate = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int albumTrackListTempelate = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AlbumView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int artistListTemplate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ArtistView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int similarListTemplate = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int trackListTempelate = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TrackView = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
